### ISSUE TITLE
Crashing when opening parts

### ISSUE THREAD

**Issue by fotis400** [RobotsWar/Plater#32]
I use Fedora 21 x86_64 with Gnome 3.14.

Whenever I try to add a second part the program crashes. The first part is inserted correctly, on the second one there is the problem.

I do not get any terminal output, neither I find any relevant logs. The "Open" window just stays there freezed, and the main app window dissapears.

**Comment by fotis400** [comment]
I also just tried to click "Add part", then cancel. Then clicked "Add Part" again and the program crashed again without importing any file. 

Seems there is a problem with the add part dialog when executing for second time, not with loading the files themselves...

I tried with many different parts (small and large).

**Comment by Gregwar** [comment]
Hello,
What version are you running?
Does it works if you click "add part" and select multiple part in the same operation and then click ok?

**Comment by Gregwar** [comment]
There was indeed some bugs in the GUI, may you try with the master version?

**Comment by fotis400** [comment]
Ok I was using the pre-compiled binary.

I just tried pulling master, and it works correctly. Both adding multiple times, or when selecting multiple files.

**Comment by Gregwar** [comment]
Ok
Thanks for reporting anyway, I'll try to make a new release
