### ISSUE TITLE
Command Line Usage in Pre-Packaged Binaries

### ISSUE THREAD

**Issue by masterperson40** [RobotsWar/Plater#34]
After downloading the pre-packed binaries (specifically for Linux) I ran "./Plater -v plater.conf" however, instead of it starting, it just opened the GUI. However, after building it myself, the same command starts plater like it should without opening the GUI.

**Comment by Gregwar** [comment]
Actuallu you have two binary, one in src that can be built using cmake and the gui
Both use the same library as a backend, but one is command line and the other os a gui using qt

**Comment by masterperson40** [comment]
Is there possibility of the command line binaries being released along with the GUI binaries?

**Comment by Gregwar** [comment]
What is your use case?

**Comment by masterperson40** [comment]
We use Plater in [our software](https://github.com/masterperson40/retr3d/#plate) in the background to plate objects. However, since this feature is optional, we feel that users should be able to "install" this feature themselves. The only thing that is preventing this right now is that, users must compile their own versions of Plater, which is a bit over most of our target audience's heads.

**Comment by Gregwar** [comment]
If you use it in background you can link your own softwarz against the plater library built by the cmake and use the internal api (not really well documented)
this is how the gui works
Or build the command line tool and invoke it

**Comment by masterperson40** [comment]
Okay, thank you for your help.
