### ISSUE TITLE
Orientation sometimes ignored (mac)

### ISSUE THREAD

**Issue by Maaphoo** [RobotsWar/Plater#35]
I have built Plater for command line use on Mac. The issue is that some, but not all, of the stl files I try to plate in a particular orientation get plated only in their original orientation. For example, "PBBHR.stl 2 back" is plated as if "PBBHR.stl 2 bottom" was used in plater.conf. It is probably not related, but I did have to include unistd.h in util.cpp to get Plater to compile. Thanks, Plater is great.

-Matt
OSX 10.10.4

**Comment by Gregwar** [comment]
Hello
Can you provide a particular example that produces the bug?

**Comment by Maaphoo** [comment]
Here is a link to the files that produce an example of the error. PBBHR.stl is the original STL file. Plate-001.stl is the output. plater is the unix executable I built for mac and used along with plater.conf. Let me know if you need anything else.

[plater example](https://drive.google.com/folderview?id=0B5HsbvUipi3gfldua1hzR3h6VGk5UUktaUpaMjN4ay1wT29pRWlCclZOMG9UZS1sblA0T1k&usp=sharing)

**Comment by Gregwar** [comment]
Ok, got it, this is because your text editor end lines with ``\r\n`` instead of ``\n``
So, the orientation is ``back\r`` instead of ``back``
I'll add a check for that

**Comment by Maaphoo** [comment]
Excellent. Thanks for the help!

**Comment by Gregwar** [comment]
Should be fixed in master, can you confirm?

**Comment by Gregwar** [comment]
Sorry, re-pushed using custom trim() instead,
can you confirm that master works?
Thanks :-)

**Comment by Maaphoo** [comment]
Will do.

**Comment by Maaphoo** [comment]
Works perfect!. Compiles without any additions too. Thanks a bunch for the super fast help.
